[package]
name = "aoc_2025_lib"
version.workspace = true
edition.workspace = true

[dependencies]
regex.workspace = true

[dev-dependencies]
rand.workspace = true
criterion.workspace = true

[[bench]]
name = "blink"
harness = false
